### ISSUE TITLE
chore(calls): improve call experience overall

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1466] opened 2023-11-06 21:53 UTC
Usually, when we try out calls or works great or works not as great, this ticket is to investigate and improve that flow.

**Comment by sdwoodbury** [comment] 2023-11-07 13:58
i need something more specific than this. as for it "not working", seems like a duplicate of #1409

**Comment by tooshel** [comment] 2023-11-07 17:24
We will make a better ticket with specific improvements.

**Closed as completed** 2023-11-07 17:24 UTC
Labels: new ticket :boom:
